auth:
  postgresPassword: postgres

primary:
  persistence:
    enabled: true
    size: 1Gi

  service:
    type: ClusterIP

  podSecurityContext:
    enabled: true
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001

  initdb:
    user: postgres
    password: postgres
    scripts:
      01-init.sql: |
        CREATE USER customer_user WITH ENCRYPTED PASSWORD 'customer_pass';
        CREATE DATABASE customer_db OWNER customer_user;

        CREATE USER auth_user WITH ENCRYPTED PASSWORD 'auth_pass';
        CREATE DATABASE auth_db OWNER auth_user;

metrics:
  enabled: true
  serviceMonitor:
    enabled: true