{{- if .Values.authService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homework-apps.authFullname" . }}
  labels:
    {{- include "homework-apps.authLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
type: {{ .Values.common.secretType | default "Opaque" }}
stringData:
  DB_USER: {{ .Values.authService.secret.dbUser }}
  DB_PASSWORD: {{ .Values.authService.secret.dbPassword }}
  Jwt__PrivateKeyPem: |-
{{ .Values.authService.secret.jwtPrivateKeyPem | nindent 4 }}
  Jwt__KeyId: {{ .Values.authService.secret.jwtKeyId | quote }}
{{- end }}
