{{- if .Values.authService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework-apps.authFullname" . }}
  labels:
    {{- include "homework-apps.authLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "homework-apps.authSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.authService.service.port }}
      targetPort: {{ .Values.authService.deployment.port }}
      protocol: {{ .Values.authService.service.protocol }}
      name: {{ .Values.authService.service.name }}
    {{- if .Values.authService.service.monitor.enabled }}
    - port: {{ .Values.authService.service.monitor.port }}
      targetPort: {{ .Values.authService.deployment.port }}
      protocol: {{ .Values.authService.service.monitor.protocol }}
      name: {{ .Values.authService.service.monitor.name }}
    {{- end }}
  type: {{ .Values.authService.service.type }}
{{- end }}
