{{- if .Values.customerService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework-apps.customerFullname" . }}
  labels:
    {{- include "homework-apps.customerLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "homework-apps.customerSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.customerService.service.port }}
      targetPort: {{ .Values.customerService.deployment.port }}
      protocol: {{ .Values.customerService.service.protocol }}
      name: {{ .Values.customerService.service.name }}
    {{- if .Values.customerService.service.monitor.enabled }}
    - port: {{ .Values.customerService.service.monitor.port }}
      targetPort: {{ .Values.customerService.deployment.port }}
      protocol: {{ .Values.customerService.service.monitor.protocol }}
      name: {{ .Values.customerService.service.monitor.name }}
    {{- end }}
  type: {{ .Values.customerService.service.type }}
{{- end }}
