{{- if and .Values.customerService.enabled .Values.customerService.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "homework-apps.customerFullname" . }}
  labels:
    {{- include "homework-apps.customerLabels" . | nindent 4 }}
spec:
  endpoints:
    - port: {{ .Values.customerService.service.monitor.name }}
      scrapeTimeout: {{ .Values.customerService.serviceMonitor.scrapeTimeout }}
      path: {{ .Values.customerService.serviceMonitor.path }}
      honorLabels: {{ .Values.customerService.serviceMonitor.honorLabels }}
      scheme: http
  selector:
    matchLabels:
      {{- include "homework-apps.customerSelectorLabels" . | nindent 6 }}
{{- end }}
