apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "customer-service.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
data:
  DB_HOST: {{ .Values.config.dbHost }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName }}
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.environment }}