apiVersion: v1
kind: Service
metadata:
  name: {{ include "customer-service.fullname" . }}
  labels:
    {{- include "customer-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "customer-service.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.port }}
    protocol: {{ .Values.service.protocol }}
    name: {{ .Values.service.name }}
  - port: {{ .Values.service.monitor.port }}
    targetPort: {{ .Values.deployment.port }}
    protocol: {{ .Values.service.monitor.protocol }}
    name: {{ .Values.service.monitor.name }}
  type: {{ .Values.service.type }}
