{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
data:
  DB_HOST: {{ .Values.global.dbHost }}
  DB_PORT: {{ .Values.global.dbPort | quote }}
  DB_NAME: {{ .Values.dbName }}
  ASPNETCORE_ENVIRONMENT: {{ .Values.global.environment }}
  Ms__Customer__BaseUrl: {{ default (include "auth-service.customerServiceUrl" .) .Values.config.msCustomerBaseUrlOverride | quote }}
  Ms__Customer__Timeout: {{ .Values.config.msCustomerTimeout | quote }}
  Jwt__Issuer: {{ default (include "auth-service.authServiceUrl" .) .Values.config.jwtIssuerOverride | quote }}
  Jwt__LifetimeMinutes: {{ .Values.config.jwtLifetimeMinutes | quote }}
{{- end }}
