{
 "title": "customer-service dashboard",
 "time": { "from": "2026-03-30T14:22:00.000Z", "to": "2026-03-30T14:47:59.000Z" },
 "panels": [
  {
   "title": "99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint, action, code) (\r\n    rate(http_request_duration_seconds_bucket{controller=\"Customers\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint, action, code) (\r\n    rate(http_request_duration_seconds_bucket{controller=\"Customers\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "50 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le, endpoint, action, code) (\r\n    rate(http_request_duration_seconds_bucket{controller=\"Customers\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint, action, code) (\r\n  rate(http_requests_received_total{code=\"200\", action=~\"Delete|Post|Put\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rps per endpoint + action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (endpoint, action) (\r\n  rate(http_requests_received_total{endpoint!~\"/health/.*\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rps per pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(http_requests_received_total{endpoint!~\"/health/.*\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"customer-service\",\r\n    pod=~\"customer-service-.*\"\r\n  }[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"customer-service\",\r\n    pod=~\"customer-service-.*\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "threadpool throughput per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(system_runtime_threadpool_completed_items_count_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "threadpool max per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "max by (pod) (max_over_time(system_runtime_threadpool_thread_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "threadpool queue per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "max by (pod) (max_over_time(system_runtime_threadpool_queue_length[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "db active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"customers_db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "db cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(pg_stat_database_blks_hit{datname=\"customers_db\"}[5m]))\r\n  /\r\n  (\r\n    sum(rate(pg_stat_database_blks_hit{datname=\"customers_db\"}[5m])) +\r\n    sum(rate(pg_stat_database_blks_read{datname=\"customers_db\"}[5m]))\r\n  )\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by (datname) (\r\n  rate(pg_stat_database_xact_commit{datname=\"customers_db\"}[1m]) +\r\n  rate(pg_stat_database_xact_rollback{datname=\"customers_db\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}