global:
  umbrellaChartName: homework-apps
  kubernetesAppName: homework-apps
  peerAuthName: auth
  peerCustomerName: customer
  clusterDomain: cluster.local
  secretType: Opaque
  dbHost: postgres-postgresql
  dbPort: "5432"
  environment: Development
  kafkaBootstrapServers: ""
  kafkaClusterReleaseName: kafka

enabled: true
name: notification
dbName: notification_db

deployment:
  imageRepository: maslovdeveloper/hwapp-notification-service
  imageTag: "1.0"
  replicaCount: 2
  maxSurge: 1
  maxUnavailable: 1
  port: 8000
  protocol: TCP
  startupProbe:
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
  readinessProbe:
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

service:
  type: ClusterIP
  port: 80
  protocol: TCP
  name: http

migrationJob:
  enabled: true
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  imageRepository: maslovdeveloper/hwapp-notification-migration
  imageTag: "1.0"

config:
  authUrlOverride: ""
  kafkaGroupId: notification-service
  kafkaTopics:
    - customers
    - orders

secret:
  dbUser: notification_user
  dbPassword: notification_pass
