yamlApplicationConfig:
  kafka:
    clusters:
      - name: local
        bootstrapServers: kafka-controller-headless.customer-service.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false