{{- if and .Values.ingress.enabled .Values.authService.enabled .Values.traefik.middlewares.rateLimitAuth.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "homework-apps.fullname" . }}-auth-rate-limit
  labels:
    {{- include "homework-apps.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && Path(`/api/auth/login`) && Method(`POST`)
      kind: Rule
      priority: 100
      middlewares:
        {{- if .Values.traefik.middlewares.requestId.enabled }}
        - name: {{ include "homework-apps.traefikRequestIdMiddlewareName" . }}
        {{- end }}
        - name: {{ include "homework-apps.traefikRateLimitAuthMiddlewareName" . }}
      services:
        - name: {{ include "homework-apps.serviceFullnameByKey" (list . "authService") }}
          port: {{ .Values.authService.service.port }}
    - match: Host(`{{ .Values.ingress.host }}`) && Path(`/api/auth/register`) && Method(`POST`)
      kind: Rule
      priority: 100
      middlewares:
        {{- if .Values.traefik.middlewares.requestId.enabled }}
        - name: {{ include "homework-apps.traefikRequestIdMiddlewareName" . }}
        {{- end }}
        - name: {{ include "homework-apps.traefikRateLimitAuthMiddlewareName" . }}
      services:
        - name: {{ include "homework-apps.serviceFullnameByKey" (list . "authService") }}
          port: {{ .Values.authService.service.port }}
{{- end }}
