{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
type: {{ .Values.global.secretType | default "Opaque" }}
stringData:
  DB_USER: {{ .Values.secret.dbUser }}
  DB_PASSWORD: {{ .Values.secret.dbPassword }}
  ADMIN_LOGIN: {{ .Values.secret.adminLogin | quote }}
  ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
  Jwt__PrivateKeyPem: |-
{{ .Values.secret.jwtPrivateKeyPem | nindent 4 }}
  Jwt__KeyId: {{ .Values.secret.jwtKeyId | quote }}
{{- end }}
