global:
  umbrellaChartName: homework-apps
  kubernetesAppName: homework-apps
  peerAuthName: auth
  peerBillingName: billing
  peerWarehouseName: warehouse
  peerDeliveryName: delivery
  clusterDomain: cluster.local
  secretType: Opaque
  dbHost: postgres-postgresql
  dbPort: "5432"
  environment: Development
  kafkaBootstrapServers: ""
  kafkaClusterReleaseName: kafka

enabled: true
name: order
dbName: order_db

deployment:
  imageRepository: maslovdeveloper/hwapp-order-service
  imageTag: "7.0"
  replicaCount: 2
  maxSurge: 1
  maxUnavailable: 1
  port: 8000
  protocol: TCP
  startupProbe:
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
  readinessProbe:
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

service:
  type: ClusterIP
  port: 80
  protocol: TCP
  name: http

migrationJob:
  enabled: true
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  imageRepository: maslovdeveloper/hwapp-order-migration
  imageTag: "7.0"

config:
  authUrlOverride: ""
  msBillingBaseUrlOverride: ""
  msBillingTimeout: "00:00:10"
  msWarehouseBaseUrlOverride: ""
  msWarehouseTimeout: "00:00:10"
  msDeliveryBaseUrlOverride: ""
  msDeliveryTimeout: "00:00:10"
  orderSagaBatchSize: 10
  orderSagaLockDuration: "00:01:00"
  orderSagaPollingInterval: "00:00:05"
  kafkaAcks: "All"
  kafkaEnableIdempotence: true

secret:
  dbUser: order_user
  dbPassword: order_pass
