global:
  umbrellaChartName: homework-apps
  kubernetesAppName: homework-apps
  peerAuthName: auth
  clusterDomain: cluster.local
  secretType: Opaque
  dbHost: postgres-postgresql
  dbPort: "5432"
  environment: Development

enabled: true
name: warehouse
dbName: warehouse_db

deployment:
  imageRepository: maslovdeveloper/hwapp-warehouse-service
  imageTag: "8.1"
  replicaCount: 2
  maxSurge: 1
  maxUnavailable: 1
  port: 8000
  protocol: TCP
  startupProbe:
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
  readinessProbe:
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

service:
  type: ClusterIP
  port: 80
  protocol: TCP
  name: http
  monitor:
    enabled: true
    port: 8080
    protocol: TCP
    name: monitor

serviceMonitor:
  enabled: true
  scrapeTimeout: 30s
  honorLabels: true
  path: /metrics

migrationJob:
  enabled: true
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  imageRepository: maslovdeveloper/hwapp-warehouse-migration
  imageTag: "10.1"

config:
  authUrlOverride: ""
  kafkaGroupId: warehouse-service
  kafkaTopics:
    - products
  kafkaWarehouseStockTopic: stocks
  kafkaAcks: "All"
  kafkaEnableIdempotence: true

secret:
  dbUser: warehouse_user
  dbPassword: warehouse_pass
