{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customer-service.fullname" . }}
  labels:
    {{- include "customer-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
type: {{ .Values.global.secretType | default "Opaque" }}
stringData:
  DB_USER: {{ .Values.secret.dbUser }}
  DB_PASSWORD: {{ .Values.secret.dbPassword }}
{{- end }}
