{{- if and .Values.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "customer-service.fullname" . }}
  labels:
    {{- include "customer-service.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: {{ .Values.service.monitor.name }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      path: {{ .Values.serviceMonitor.path }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      scheme: http
  selector:
    matchLabels:
      {{- include "customer-service.selectorLabels" . | nindent 6 }}
{{- end }}
