{{- if .Values.customerService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homework-apps.customerFullname" . }}
  labels:
    {{- include "homework-apps.customerLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
type: {{ .Values.common.secretType | default "Opaque" }}
stringData:
  DB_USER: {{ .Values.customerService.secret.dbUser }}
  DB_PASSWORD: {{ .Values.customerService.secret.dbPassword }}
{{- end }}
