FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .
RUN dotnet publish CustomerService.DbMigrator/CustomerService.DbMigrator.csproj -c Release -o /app/publish

# runtime
FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "CustomerService.DbMigrator.dll"]